AWSTemplateFormatVersion: '2010-09-09'
Description: 'nodejs Project Infrastructure'
Parameters:
  S3BucketName:
   Type: String
   Description: Enter the name of s3bucket where the Cloudformation stacks are
  VpcBlock:
    Type: String
    Default: 172.10.0.0/16
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.

  PublicSubnet01Block:
    Type: String
    Default: 172.10.0.0/24
    Description: The CIDR block for the public subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PublicSubnet02Block:
    Type: String
    Default: 172.10.1.0/24
    Description: The CIDR block for the public subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet01Block:
    Type: String
    Default: 172.10.2.0/24
    Description: The CIDR block for the private subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet02Block:
    Type: String
    Default: 172.10.3.0/24
    Description: The CIDR block for the private subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet03Block:
    Type: String
    Default: 172.10.4.0/24
    Description: The CIDR block for the private subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet04Block:
    Type: String
    Default: 172.10.5.0/24
    Description: The CIDR block for the private subnet located in Availability Zone.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
  
  env:
    Type: String
  

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.amazonaws.com/aws-eks-vpc-public-private-subnets.yaml
      TimeoutInMinutes: 20
      Parameters:
        VpcBlock: !Ref VpcBlock
        PublicSubnet01Block: !Ref PublicSubnet01Block
        PublicSubnet02Block: !Ref PublicSubnet02Block
        PrivateSubnet01Block: !Ref PrivateSubnet01Block
        PrivateSubnet02Block: !Ref PrivateSubnet02Block
        PrivateSubnet03Block: !Ref PrivateSubnet03Block
        PrivateSubnet04Block: !Ref PrivateSubnet04Block
        env: !Ref env

Outputs:
  VpcStackRef:
    Value: !Ref VpcStack
  SubnetIDs:
    Value: !GetAtt VpcStack.Outputs.SubnetIds
  SecurityGroup:
    Value: !GetAtt VpcStack.Outputs.SecurityGroups
  VpcId:
   Value: !GetAtt VpcStack.Outputs.VpcId